# ----------------------------------------------------------
# Fonts
# ----------------------------------------------------------

font_family      Maple Mono NF CN
bold_font        Maple Mono NF CN Bold
italic_font      Maple Mono NF CN Italic
bold_italic_font Maple Mono NF CN Bold Italic

font_size 12.0

# 调整中文/亚洲字符的垂直对齐和宽度
disable_ligatures never
font_features Maple Mono NF CN +zero +ss01 +ss02 +ss03 +cv01 +cv02

# 调整行高、字符宽度（让中英文 2:1 看起来更舒服）
modify_font cell_height 110%
modify_font baseline 1

# 符号字体兜底（Nerd Font 图标 + emoji）
symbol_map U+E000-U+E00A,U+EA60-U+EBEB,U+E0A0-U+E0A2,U+E0B0-U+E0B3,U+E5FA-U+E62B Symbols Nerd Font Mono
symbol_map U+1F300-U+1F9FF Noto Color Emoji


# ----------------------------------------------------------
# Animations
# ----------------------------------------------------------

# 光标拖尾
cursor_trail                  3
cursor_trail_decay            0.1 0.4
cursor_trail_start_threshold  2


# ----------------------------------------------------------
# Keys
# ----------------------------------------------------------

# 复制粘贴
map alt+c copy_to_clipboard
map alt+v paste_from_clipboard
