include="~/.config/fuzzel/fuzzel_theme.ini"
font=Maple Mono NF CN:weight=medium
# fuzzel 把 terminal= 整段当成"前缀",再追加 .desktop 的 Exec 命令
# 所以这里必须写到"接命令的形态",wezterm 用 `start --` 或 `-e` 都行
terminal=wezterm start --
prompt=">>  "
layer=overlay

[border]
radius=17
width=1

[dmenu]
exit-immediately-if-empty=yes
